using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using cstsd.Lexical.Core;
using ToTypeScriptD.Core;
using ToTypeScriptD.Core.Extensions;
using ToTypeScriptD.Lexical.TypeScript;


namespace cstsd
{
    public class RenderTypescript
    {

        public static void FromAssemblies(ICollection<string> assemblyPaths, TsWriterConfig config, TextWriter w)
        {
            foreach (var aPath in assemblyPaths)
            {
                FromAssembly(aPath, config, w);
            }
        }
        

        //TODO: typescriptexport attribute - flag to do all or look for attribute? what about namespace-level exports? inherited attribute? 
        public static void FromAssembly(string assemblyPath, TsWriterConfig config, TextWriter w)
        {
            var css = new CsTypeScanner();

            w.Write(GetHeader(new[] { assemblyPath }, config.IncludeSpecialTypes));
            
            var netAssembly = css.RegisterAssembly(assemblyPath);


            
        }

        
        //TODO: option to include referenced types that are in external assemblies (or how to handle assembly not founds)
        public static void FromTypes<T>(ICollection<Type> types, TextWriter w, TsWriterConfig config, ITypeScanner<T> typeScanner, INetWriter tsWriter)
        {
            var namespaces = types.Select(t => t.Namespace).Distinct();

            foreach (var ns in namespaces)
            {
                //w.Write(tsWriter.Write(ns) + config.NewLines(2));
            }
        }






        private static string GetHeader(IEnumerable<string> assemblyPaths, bool forceDueToSpecialType)
        {
            if (!forceDueToSpecialType && !assemblyPaths.Any())
            {
                return "";
            }

            if (!assemblyPaths.All(File.Exists))
            {
                return "";
            }

            var sb = new StringBuilder();
            sb.AppendLine("//****************************************************************");
            sb.AppendLine("//  Generated by:  ToTypeScriptD");
            sb.AppendLine("//  Website:       http://github.com/ToTypeScriptD/ToTypeScriptD");
            sb.AppendLine($"//  Version:       {System.Diagnostics.FileVersionInfo.GetVersionInfo(typeof (RenderTypescript).Assembly.Location).ProductVersion}");
            sb.AppendLine($"//  Date:          {DateTime.Now}");
            if (assemblyPaths.Any())
            {
                sb.AppendLine("//");
                sb.AppendLine("//  Assemblies:");
                assemblyPaths
                    .Select(System.IO.Path.GetFileName)
                    .Distinct()
                    .OrderBy(s => s)
                    .Each(path =>
                    {
                        sb.AppendLine($"//    {Path.GetFileName(path)}");
                    });
                sb.AppendLine("//");
            }
            sb.AppendLine("//****************************************************************");
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine();
            return sb.ToString();
        }



    }
}
